// <auto-generated />
using System;
using Crystal_Clinic_Mgm.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crystal_Clinic_Mgm.Persistence.Migrations.ERP_Db
{
    [DbContext(typeof(ERP_DbContext))]
    [Migration("20250420074205_erp_initial")]
    partial class erp_initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.AccountTracking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("BalanceAmount")
                        .HasColumnType("real")
                        .HasColumnName("BalanceAmount");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<float>("CreditAmount")
                        .HasColumnType("real")
                        .HasColumnName("CreditAmount");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyTypeId");

                    b.Property<float>("DebitAmount")
                        .HasColumnType("real")
                        .HasColumnName("DebitAmount");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("MainAccountId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("MainAccountId");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("TransactionDate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.Property<int>("trackType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("MainAccountId");

                    b.ToTable("AccountTracking", "AssetMS");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.ExpenseTracking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("Amount")
                        .HasColumnType("real")
                        .HasColumnName("Amount");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyTypeId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime")
                        .HasColumnName("Date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ExpenseTypeId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("MainAccountId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("MainAccountId");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("MainAccountId");

                    b.ToTable("ExpenseTracking", "AssetMS");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.MainAccount", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ID");

                    b.Property<int?>("AssetTypeId")
                        .HasColumnType("int")
                        .HasColumnName("AssetTypeId");

                    b.Property<float>("BalanceAmount")
                        .HasColumnType("real")
                        .HasColumnName("BalanceAmount");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyTypeId");

                    b.Property<DateTime>("DepositDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("DepositDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("OwnerUserId");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ParentId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<float>("TotalCreditAmount")
                        .HasColumnType("real")
                        .HasColumnName("TotalCreditAmount");

                    b.Property<float>("TotalDebitAmount")
                        .HasColumnType("real")
                        .HasColumnName("TotalDebitAmount");

                    b.HasKey("ID");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("ParentId");

                    b.ToTable("MainAccount", "AssetMS");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.TradeTracking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyTypeId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime")
                        .HasColumnName("Date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<float>("LossAmount")
                        .HasColumnType("real")
                        .HasColumnName("LossAmount");

                    b.Property<Guid>("MainAccountId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("MainAccountId");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<float>("ProfitAmount")
                        .HasColumnType("real")
                        .HasColumnName("ProfitAmount");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<float>("TradeAmount")
                        .HasColumnType("real")
                        .HasColumnName("TradeAmount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("MainAccountId");

                    b.ToTable("TradeTracking", "AssetMS");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.WithdrawalTracking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyTypeId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime")
                        .HasColumnName("Date");

                    b.Property<float>("DepositAmount")
                        .HasColumnType("real")
                        .HasColumnName("DepositAmount");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("MainAccountId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("MainAccountId");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.Property<float>("WithdrawalAmount")
                        .HasColumnType("real")
                        .HasColumnName("WithdrawalAmount");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("MainAccountId");

                    b.ToTable("WithdrawalTracking", "AssetMS");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.General.News", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AttachmentPath");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("EndTime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Location");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<DateTime>("NewsDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("NewsDate");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<bool?>("ShowNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ShowNotification");

                    b.Property<string>("Speaker")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Speaker");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("StartTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Title");

                    b.HasKey("ID");

                    b.ToTable("News", "General");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.General.NewsNotification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("NewsId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsNotification", "General");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.General.TrainingVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Application");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariTitle");

                    b.Property<string>("DariVideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DariVideoPath");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoTitle");

                    b.Property<string>("PashtoVideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PashtoVideoPath");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Poster");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("Id");

                    b.ToTable("TrainingVideos", "General");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.AdvancePayment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("AdvanceAmount")
                        .HasColumnType("real")
                        .HasColumnName("AdvanceAmount");

                    b.Property<DateTime>("AdvanceDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("AdvanceDate");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyTypeId");

                    b.Property<float>("EachInstallmentAmount")
                        .HasColumnType("real")
                        .HasColumnName("EachInstallmentAmount");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("MainAccountId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("MainAccountId");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<int>("PayTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PayTypeId");

                    b.Property<Guid>("PayedBy")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("PayedBy");

                    b.Property<float>("RemainingBalance")
                        .HasColumnType("real")
                        .HasColumnName("RemainingBalance");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MainAccountId");

                    b.HasIndex("PayTypeId");

                    b.ToTable("AdvancePayment", "HR");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.ContractDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ContractTypeId");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyTypeId");

                    b.Property<int>("EmployeeProfileId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeProfileId");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("EndDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<int>("PositionTitleId")
                        .HasColumnType("int")
                        .HasColumnName("PositionTitleId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<float>("SalaryAmount")
                        .HasColumnType("real")
                        .HasColumnName("SalaryAmount");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("EmployeeProfileId");

                    b.HasIndex("PositionTitleId");

                    b.ToTable("ContractDetails", "HR");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.EmployeeProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("BloodGroup");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int?>("CurrencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyTypeId");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DateTime")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("EmergencyPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EmergencyPhoneNumber");

                    b.Property<string>("EnglishFatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishFatherName");

                    b.Property<string>("EnglishFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishFirstName");

                    b.Property<string>("EnglishGrandFatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishGrandFatherName");

                    b.Property<string>("EnglishSurName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishSurName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Gender");

                    b.Property<bool>("HasAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("HasAccount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsCurrent");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("JoinDate");

                    b.Property<string>("JoldNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("JoldNo");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("LeaveDate");

                    b.Property<string>("LeaveRemark")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("LeaveRemark");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PageNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PageNo");

                    b.Property<string>("PashtoFatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoFatherName");

                    b.Property<string>("PashtoFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoFirstName");

                    b.Property<string>("PashtoGrandFatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoGrandFatherName");

                    b.Property<string>("PashtoSurName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoSurName");

                    b.Property<string>("PermenantAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PermenantAddress");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PersonalEmail");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PhotoPath");

                    b.Property<string>("RegNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("RegNo");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<string>("TazkiraNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TazkiraNo");

                    b.Property<int>("TazkiraTypeId")
                        .HasColumnType("int")
                        .HasColumnName("TazkiraTypeId");

                    b.Property<string>("TemporaryAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TemporaryAddress");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("CurrencyTypeId");

                    b.ToTable("EmployeeProfile", "HR");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.PayrollTracking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("AdvanceDeduction")
                        .HasColumnType("real")
                        .HasColumnName("AdvanceDeduction");

                    b.Property<float>("BaseSalary")
                        .HasColumnType("real")
                        .HasColumnName("BaseSalary");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<int>("ContractDetailsId")
                        .HasColumnType("int")
                        .HasColumnName("ContractDetailsId");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int?>("CurrencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyTypeId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime")
                        .HasColumnName("Date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsPayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsPayed");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<float>("NetSalary")
                        .HasColumnType("real")
                        .HasColumnName("NetSalary");

                    b.Property<int?>("PayTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PayTypeId");

                    b.Property<Guid?>("PayedBy")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("PayedBy");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.HasIndex("ContractDetailsId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayTypeId");

                    b.ToTable("PayrollTracking", "HR");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HRLooks.ContractType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.ToTable("ContractType", "HRLooks");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HRLooks.Partners", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameInEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInPashto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HRLooks.PositionTitle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("BranchId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.ToTable("PositionTitle", "HRLooks");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Look.AssetType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.ToTable("AssetType", "Look");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Look.Attachments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AttachmentDescription");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("FileExtention")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Comments");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("FilePath");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("Id");

                    b.ToTable("Attachments", "General");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.HasIndex("ParentId");

                    b.ToTable("Branch", "Look");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.ToTable("CurrencyType", "Look");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Look.ExpenseType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.ToTable("ExpenseType", "Look");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Look.LoanType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.ToTable("LoanType", "Look");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Look.PayType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.ToTable("PayType", "Look");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.Assignment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("EndDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("PropertyId");

                    b.ToTable("Assignment", "PropertyMS");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.Maintenance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime")
                        .HasColumnName("Date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<float?>("PayedAmountInUSD")
                        .HasColumnType("real")
                        .HasColumnName("PayedAmountInUSD");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.HasIndex("PropertyId");

                    b.ToTable("Maintenance", "PropertyMS");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.Payment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("AmountPaid")
                        .HasColumnType("real")
                        .HasColumnName("AmountPaid");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("PaymentDate");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("PropertyId");

                    b.Property<float>("RemainingBalance")
                        .HasColumnType("real")
                        .HasColumnName("RemainingBalance");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Status");

                    b.HasKey("ID");

                    b.HasIndex("PropertyId");

                    b.ToTable("Payment", "PropertyMS");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.Property", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("AmountPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f)
                        .HasColumnName("AmountPaid");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Details");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PaymentStatus");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("Price");

                    b.Property<int>("PropertyConditionID")
                        .HasColumnType("int")
                        .HasColumnName("PropertyConditionID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PropertyConditionID");

                    b.ToTable("Property", "PropertyMS");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.PropertyLooks.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.ToTable("Category", "Look");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.PropertyLooks.PropertyCondition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("DariName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("DariName");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("EnglishName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("DateTime")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PashtoName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PashtoName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Remarks");

                    b.HasKey("ID");

                    b.ToTable("PropertyCondition", "Look");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.AccountTracking", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.MainAccount", "MainAccount")
                        .WithMany()
                        .HasForeignKey("MainAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CurrencyType");

                    b.Navigation("MainAccount");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.ExpenseTracking", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.MainAccount", "MainAccount")
                        .WithMany()
                        .HasForeignKey("MainAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CurrencyType");

                    b.Navigation("ExpenseType");

                    b.Navigation("MainAccount");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.MainAccount", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.MainAccount", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssetType");

                    b.Navigation("Branch");

                    b.Navigation("CurrencyType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.TradeTracking", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.MainAccount", "MainAccount")
                        .WithMany()
                        .HasForeignKey("MainAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CurrencyType");

                    b.Navigation("MainAccount");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.WithdrawalTracking", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.MainAccount", "MainAccount")
                        .WithMany()
                        .HasForeignKey("MainAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CurrencyType");

                    b.Navigation("MainAccount");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.General.NewsNotification", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.General.News", "News")
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.AdvancePayment", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.EmployeeProfile", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.AssetMS.MainAccount", "MainAccount")
                        .WithMany()
                        .HasForeignKey("MainAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.PayType", "PayType")
                        .WithMany()
                        .HasForeignKey("PayTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CurrencyType");

                    b.Navigation("Employee");

                    b.Navigation("MainAccount");

                    b.Navigation("PayType");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.ContractDetails", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.HR.HRLooks.ContractType", "ContractType")
                        .WithMany()
                        .HasForeignKey("ContractTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.EmployeeProfile", "EmployeeProfile")
                        .WithMany()
                        .HasForeignKey("EmployeeProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.HR.HRLooks.PositionTitle", "PositionTitle")
                        .WithMany()
                        .HasForeignKey("PositionTitleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ContractType");

                    b.Navigation("CurrencyType");

                    b.Navigation("EmployeeProfile");

                    b.Navigation("PositionTitle");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.EmployeeProfile", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Branch");

                    b.Navigation("CurrencyType");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.PayrollTracking", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.ContractDetails", "ContractDetails")
                        .WithMany()
                        .HasForeignKey("ContractDetailsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.HR.HR.EmployeeProfile", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.PayType", "PayType")
                        .WithMany()
                        .HasForeignKey("PayTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Branch");

                    b.Navigation("ContractDetails");

                    b.Navigation("CurrencyType");

                    b.Navigation("Employee");

                    b.Navigation("PayType");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.HR.HRLooks.PositionTitle", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Look.Branch", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.Assignment", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Properties.Property", null)
                        .WithMany("Assignments")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.Maintenance", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Properties.Property", null)
                        .WithMany("Maintenances")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.Payment", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Properties.Property", null)
                        .WithMany("Payments")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.Property", b =>
                {
                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Properties.PropertyLooks.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Crystal_Clinic_Mgm.Domain.Entities.Properties.PropertyLooks.PropertyCondition", "Condition")
                        .WithMany()
                        .HasForeignKey("PropertyConditionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Condition");
                });

            modelBuilder.Entity("Crystal_Clinic_Mgm.Domain.Entities.Properties.Property", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Maintenances");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
